### ISSUE TITLE
App Crash Just before Sending Firo

### ISSUE THREAD

**Issue by Stuwartserver** [firoorg/mobile#14]
When i try To take out My Firo The App Crash So its stuck ? I just loose my firo or what? THEY NEED TO FIX THIS I DONT WANT TO LOOSE MY FIRO

**Comment by hzak** [comment]
@Stuwartserver thanks for raising the issue. Now we are working on investigating and fixing it. You will not lose your firos.

**Comment by bouncethebox** [comment]
Same here, but some color and context.  For me, the app crashes after tapping 'Confirm' and it changes to 'Confirming' and animates and after about 3 seconds it closes.  My transaction was constructed to 'Max' amount, with fee deducted and address both scanned and pasted. I also tried another transaction with a specified amount and another with a specified amount and no fee deduction with no luck.  

I've restored the wallet to other devices, and the problem is in the firo core app from the play store as well as the apk download able from here. 

I don't know if it helps or not, but the firo I am trying to send were obtained from solo mining over the last few weeks and the payments came in from 2miners firo solo pool.

**Comment by bouncethebox** [comment]
I'm able to restore the wallet on Campfire and send firo successfully - any idea when this will be fixed in the official wallet?

**Comment by hzak** [comment]
@Stuwartserver @bouncethebox please check the latest update

**Comment by Stuwartserver** [comment]
I was able to backup my Firo with CampFire But i just tried the newest version And it work Perfectly Tanks For Your Great Work!!

**Comment by Stuwartserver** [comment]
Tanks Firo Teams For your great Work!!!

**Comment by Stuwartserver** [comment]
Problem Solved
